### ISSUE TITLE
Config missing

### ISSUE THREAD

**Issue by bumbus** [micschk/silverstripe-chunkeduploadfield#1]
Hi there,
thanks for sharing this. It works well for me so far. It seems so that some kind of config file or folder is missing the make the manifestbuilder (silverstripe 3.1) recognize this as module. Just creating a folder named "_config" fixed this for me.

Regards
Bumbus

**Comment by micschk** [comment]
Hi, because _config was empty, Git didn't track it. Added it now, thanks for the report.

**Comment by bumbus** [comment]
Thanx for that quick fix.
Have a nice day.



Am 03.03.2015 um 10:32 schrieb Michael van Schaik <notifications@github.com>:
