### ISSUE TITLE
upload of large files not working in IE11

### ISSUE THREAD

**Issue by xini** [micschk/silverstripe-chunkeduploadfield#7]
see comments to #5 for details.

**Comment by nglanbt** [comment]
I did debug this module with SS3.6 on FF and IE11. I figure out that:
 - If I try to upload a file which file size less than the max file size in php,ini, IE11 works well
 - If I try to upload a file which file size bigger, it will show an error. And if check by dev tool I see it's http error 400 (bad request) and reason is the code is following in method upload() of class **ChunkedUploadField
       if (!$token->checkRequest($request)) {
            return $this->httpError(400);
        }**
![upload_file_error](https://user-images.githubusercontent.com/38904629/39537600-4c775310-4e64-11e8-86ae-a0b3895be110.png)

**Comment by micschk** [comment]
Thanks @xini & @nglanbt, I think I'll just close this issue for now.
It's not really fixed, but it's resolved by not using IE11 :)
And I find IE11 usage shares around 2-3%, so we should be fine.
